package com.sample
 

import drools.movieapi.MoviesApi;
import drools.main.Message;
import drools.message.RatingMessage;
import drools.message.ReviewMessage;


rule "MovieRating"
dialect "java"
	when 
		m : RatingMessage ()
	then
		System.out.println("Movie rating updated: "+ m.getMid());
		MoviesApi movie = new MoviesApi();
		movie.updateMovieRating(m.getMid(),m.getRating());		
end

rule "MovieReview"
dialect "java"
	when 
		m : ReviewMessage ()
	then
		System.out.println("Movie rating updated: "+ m.getMid());
		MoviesApi movie = new MoviesApi();
		movie.updateMovieReview(m.getMid(),m.getReview());	
end

rule "Action"
dialect "java"
	when
		m : Genre ( genre == "Action")
	then
		System.out.println("Inserting Recommendation for Action"+ m.getUserId());
		MoviesApi movie = new MoviesApi(); 
		movie.insertSingleRecommendation("Genre",m.getGenre(),m.getUserId());
end

rule "Mystery"
dialect "java"
	when
		m : Genre ( genre == "Mystery")
	then
		System.out.println("Inserting Recommendation for Mystery"+ m.getUserId());
		MoviesApi movie = new MoviesApi(); 
		movie.insertSingleRecommendation("Genre",m.getGenre(),m.getUserId());
end

rule "Romance"
dialect "java"
	when
		m : Genre ( genre == "Romance")
	then
		System.out.println("Inserting Recommendation for Romance"+ m.getUserId());
		MoviesApi movie = new MoviesApi(); 
		movie.insertSingleRecommendation("Genre",m.getGenre(),m.getUserId());
end

rule "Drama"
dialect "java"
	when
		m : Genre ( genre == "Drama")
	then
		System.out.println("Inserting Recommendation for Drama"+ m.getUserId());
		MoviesApi movie = new MoviesApi(); 
		movie.insertSingleRecommendation("Genre",m.getGenre(),m.getUserId());
end

rule "Documentary"
dialect "java"
	when
		m : Genre ( genre == "Documentary")
	then
		System.out.println("Inserting Recommendation for Documentary"+ m.getUserId());
		MoviesApi movie = new MoviesApi(); 
		movie.insertSingleRecommendation("Genre",m.getGenre(),m.getUserId());
end

rule "Animation"
dialect "java"
	when
		m : Genre ( genre == "Animation")
	then
		System.out.println("Inserting Recommendation for Animation"+ m.getUserId());
		MoviesApi movie = new MoviesApi(); 
		movie.insertSingleRecommendation("Genre",m.getGenre(),m.getUserId());
end


